version: 0.0
os: linux
files:
  - source: ./ROOT.war
    destination: /usr/local/tomcat/webapps
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: shutdown.sh
      timeout: 10000
  #  BeforeInstall:
  #    - location: backup.sh
  #      timeout: 3000
  #  AfterInstall:
  #    - location: backup.sh
  #      timeout: 3000
  ApplicationStart:
    - location: startup.sh
      timeout: 5000
permissions:
  - object: /
    pattern: "**"
    mode: 755
    owner: ec2-user
    type:
      - file