version: 0.2

  #env:
  #variables:
  # key: "value"
  #parameter-store:
  # key: "value"
  #secrets-manager:
  # key: secret-id:json-key:version-stage:version-id
  # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
  # - variable
  #git-credential-helper: yes
  #batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
#build-graph:
phases:
  #install:
  #如果您使用的是 Ubuntu 标准映像 2.0 或更高版本，则必须指定运行时版本。
  #如果您指定了运行时版本，但是使用 Ubuntu 标准映像 2.0 以外的映像，则构建将失败。
  runtime-versions:
    java: corretto11
  #commands:
  # - command
  #pre_build:
  #commands:
  # - command
  build:
    commands:
      - mvn package -DskipTests -Dmaven.javadoc.skip=true -am
      # - command
      #post_build:
      #commands:
      # - command
      #reports:
      #report-name-or-arn:
      #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - sm-shop/appspec.yml
    - sm-shop/script/*
    - sm-shop/target/*.war
    # - location
  #name: $(date +%Y-%m-%d)
  discard-paths: yes
  #base-directory: location
cache:
  paths:
    - '/root/.m2/**/*'